### PR TITLE
update workflows and Dockerfile

### PR DESCRIPTION
**Pull request by Bevisy**
update workflows and Dockerfile

    1. add new pre-release workflow for debug
    2. add new release workflow for publish
    3. simplify the dockerfile to reduce image layers and volumes

### CODE REVIEW

**Comment by freesky-edward** [comment]
LGTM 
@Bevisy Thanks for the efforts.

**Comment by Bevisy** [comment]
@freesky-edward Before merge PR, we need too add two secret enviroment variables:
```
username: ${{ secrets.DOCKER_USERNAME }}
password: ${{ secrets.DOCKER_PASSWORD }}
```
The variable DOCKER_USERNAME decide which dockerhub repo the image would to be pushed.

**Comment by Bevisy** [comment]
Latest workflow running result:
https://github.com/Bevisy/cann/actions/runs/7385357878/job/20089955264

Latest docker image:
https://hub.docker.com/repository/docker/bevisy/cann

**Comment by freesky-edward** [comment]
@Bevisy Thanks for your contribution。

**Pull request merged**
